//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBankingProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeofAddress
    {
        public int ChangeId { get; set; }
        public Nullable<int> AccountNo { get; set; }
        public string OldAddress { get; set; }
        public string NewAddress { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
